"call plug#begin('~/.vim/plugged')
call plug#begin('~/.vim/bundle')
Plug 'tpope/vim-sensible'
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
"Plug 'editorconfig/editorconfig-vim'
"Plug 'itchyny/lightline.vim'
"Plug 'junegunn/fzf'
"Plug 'junegunn/fzf.vim'
"Plug 'mattn/emmet-vim'
"Plug 'scrooloose/nerdtree'
"Plug 'terryma/vim-multiple-cursors'
"Plug 'tpope/vim-eunuch'
"Plug 'tpope/vim-surround'
"Plug 'w0rp/ale'
call plug#end()
